todo/standalone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls")),
]

todo/core/models.py
import datetime
import json
import uuid

from django.conf import settings
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone


class Task(models.Model):
    STATUS_OPEN = 1
    STATUS_CLOSED = 2
    STATUS_CANCELED = 3

    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    project = models.ForeignKey(
        "core.Project", on_delete=models.CASCADE, null=True, blank=True
    )

    status = models.IntegerField(
        default=STATUS_OPEN,
        choices=[
            (STATUS_OPEN, "Open"),
            (STATUS_CLOSED, "Closed"),
            (STATUS_CANCELED, "Canceled"),
        ],
    )
    priority = models.IntegerField(default=0)
    repeating = models.ForeignKey(
        "core.Repeating", null=True, blank=True, on_delete=models.CASCADE
    )
    external = models.ForeignKey(
        "core.URL", null=True, blank=True, on_delete=models.CASCADE
    )

    # For basic calendar date
    start = models.DateField(blank=True, null=True)
    due = models.DateField(blank=True, null=True)

    # For specific calendar times
    startAt = models.DateTimeField(blank=True, null=True)
    dueAt = models.DateTimeField(blank=True, null=True)

    createdAt = models.DateTimeField(blank=True, null=True)
    completedAt = models.DateTimeField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse("task", kwargs={"pk": self.uuid})


class Project(models.Model):
    title = models.CharField(max_length=255)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    public = models.BooleanField(default=False)
    createdOn = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return ":".join([self.title, self.owner.username])

    def get_absolute_url(self):
        return reverse("project", kwargs={"uuid": self.uuid})


class Search(models.Model):
    title = models.CharField(max_length=255)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    data = models.TextField()
    createdOn = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse("search", kwargs={"uuid": self.uuid})

    @property
    def task_set(self):
        query = json.loads(self.data)
        qs = Task.objects.filter(owner=self.owner)
        replace = {"<today>": datetime.date.today()}
        replace["<week>"] = replace["<today>"] + datetime.timedelta(days=7)

        def filter_dict(qs, query):
            print("filter_dict", query)

            for k, v in query.items():
                if v in replace:
                    query[k] = replace[v]

            return qs.filter(Q(**query))

        def filter_list(qs, query):
            print("filter_list", query)
            q_ = Q()
            for q in query:
                print("q", q)
                for k, v in q.items():
                    if v in replace:
                        q[k] = replace[v]
                q_ |= Q(**q)
            print(q_)
            return qs.filter(q_)

        if isinstance(query, list):
            return filter_list(qs, query)
        if isinstance(query, dict):
            return filter_dict(qs, query)


class Repeating(models.Model):
    data = models.TextField()


class Tag(models.Model):
    title = models.CharField(max_length=255)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    public = models.BooleanField(default=False)
    task_set = models.ManyToManyField("core.Task")


class Context(models.Model):
    title = models.CharField(max_length=255)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    location = models.TextField()
    task_set = models.ManyToManyField("core.Task")


class Note(models.Model):
    task = models.ForeignKey("core.Task", on_delete=models.CASCADE)
    body = models.TextField()


class URL(models.Model):
    url = models.URLField()

todo/core/views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.base import RedirectView, TemplateView, View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from todo.core import models


class About(TemplateView):

    template_name = "about.html"


class RedirectSearch(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        search = get_object_or_404(
            models.Search, owner=self.request.user, title__iexact=args[0]
        )
        return search.get_absolute_url()


class RedirectProject(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        print(args, kwargs)
        inbox, _ = models.Search.objects.get_or_create(
            owner=self.request.user, title__iexact="Inbox"
        )
        return inbox.get_absolute_url()


class Project(LoginRequiredMixin, ListView):
    model = models.Task

    def get_queryset(self):
        self.today = datetime.date.today()
        return (
            models.Project.objects.get(
                owner=self.request.user, uuid=self.kwargs["uuid"]
            )
            .task_set.filter(
                status=self.request.GET.get("status", models.Task.STATUS_OPEN)
            )
            .order_by("due", "start")
            .prefetch_related("tag_set", "project", "external")
        )


class Search(LoginRequiredMixin, ListView):
    model = models.Task

    def get_queryset(self):
        self.today = datetime.date.today()
        return (
            models.Search.objects.get(owner=self.request.user, uuid=self.kwargs["uuid"])
            .task_set.filter(
                status=self.request.GET.get("status", models.Task.STATUS_OPEN)
            )
            .order_by("due", "start")
            .prefetch_related("tag_set", "project", "external")
        )


class Task(LoginRequiredMixin, DetailView):
    model = models.Task

    def post(self, request, pk):
        task = get_object_or_404(models.Task, pk=pk)
        print(self.request.POST)
        if "start" in self.request.POST:
            task.start = (
                self.request.POST["start"] if self.request.POST["start"] else None
            )
            task.save()
        if "due" in self.request.POST:
            task.due = self.request.POST["due"] if self.request.POST["due"] else None
            task.save()

        if "next" in request.POST:
            return redirect(request.POST["next"])
        return redirect("project", task.project.uuid)


class TaskAdd(LoginRequiredMixin, View):
    def post(self, request):
        inbox, _ = models.Project.objects.get_or_create(
            owner=request.user, title="Inbox"
        )
        task = models.Task.objects.create(
            owner=request.user, title=request.POST["search"], project=inbox
        )
        return redirect("project", task.project.uuid)

todo/core/templates/about.html
{% extends 'base.html' %}

{% block content %}
Foo
{% endblock %}

todo/core/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <title>{% block title %}ToDo{% endblock %}</title>
  </head>
  <body>
    {% include 'navbar.inc.html' %}

    <div class="row">
        <div class="col-sm-3">
            <ul>
                {% for search in search_list|dictsort:"createdOn" %}
                <li>
                    <td><a class="badge badge-warning" href="{{search.get_absolute_url}}">{{search.title}}</a></td>
                </li>
                {% endfor %}
                {% for project in project_list|dictsort:"createdOn" %}
                <li>
                    <td><a class="badge badge-primary" href="{{project.get_absolute_url}}">{{project.title}}</a></td>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-sm-9">
          {% block content %}{% endblock %}
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script>
      $(function () {
        $('[data-toggle="popover"]').popover()
      })
    </script>
  </body>
</html>

todo/core/templates/navbar.inc.html
<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <a class="navbar-brand" href="#">ToDo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {% if not user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'login' %}">Login <span class="sr-only">(current)</span></a>
            </li>
            {% else %}
            <li class="nav-item">
               <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% endif %}
            {% if user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
             </li>
            {% endif %}
        </ul>
    </div>

    <form class="form-inline my-2 my-lg-0" action="{% url 'task-add' %}" method="POST">
        {% csrf_token %}
        <input name="search" class="form-control mr-sm-2" type="search" placeholder="Add a new task" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">New Task</button>
      </form>
</nav>